# -*- coding: utf-8 -*-
"""test assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwJ8s-6xIPGu00XpwxKjnjRCjzO2yN6T
"""

# Explain the key features of Python that make it a popular choice for
# programming

# Because it is easy to use it ,it has vast number of liraries,it is free to
# use,it has GUI(graphical user interface ) support , it has a vast community

# Describe the role of predefined keywords in Python and provide examples of how
# they are used in a program

 # they are used to define the structure and logic code and make it easy
# examples continue,break,else,elif,input

#Compare and contrast mutable and immutable objects in Python with examples

#mutable >> they can be changed after they are created
#example>>lists
list=[1,2,3,"data"]
list[3]="science"
print(list)

#immutable>>the cannot be changed after they are created
#example>>tuple

tuple=(1,2,3,"data")
tuple[3]="science"
print(tuple)("this will throw an error as it cannot be changed ")

# Discuss the different types of operators in Python and provide examples of how
# they are used
#there are 6 types of operators,they are as follow
#1..arithmetic operator
#2..relation operator
#3..logical operator
#4..bitwise operator
#5..assignment operator
#6..special operator3

#Explain the concept of type casting in Python with examples

# type casting means to change the data type of the variable in the other data
# type
#example float,int,str,bool

a="10"

type(a)

a=int(a)

type(a)

a=float(a)

type(a)

a

#How do conditional statements work in Python? Illustrate with example
#it work on the condition if the condition is correct the code will be executed
#if it is false it will be skipped
#example

count_a=10
count_b=89
if count_a>count_b:
    print("a is greater than b")
else:
  if count_b>count_a:
    print("b is greater than a")
  else:
    if count_a==count_b:
      print("a is equal to b")

count_a=100
count_b=89
if count_a>count_b:
    print("a is greater than b")
else:
  if count_b>count_a:
    print("b is greater than a")
  else:
    if count_a==count_b:
      print("a is equal to b")

count_a=10
count_b=10
if count_a>count_b:
    print("a is greater than b")
else:
  if count_b>count_a:
    print("b is greater than a")
  else:
    if count_a==count_b:
      print("a is equal to b")

# Describe the different types of loops in Python and their use cases with
# examples.
#1..For loop>>a for loop is used to iterate over a sequence|like(list,tuple)
#2..whhile loop>>it execute a set as long as the condition is true

count=5
for i in range (count):
  print(i)

count=5
while count>0:
  print(count)

